// This file is generated by Slice Machine. Update with care!

import Features from "./Features";
import Hero from "./Hero";
import TestSlice from "./TestSlice";

export { Features, Hero, TestSlice };

export const components = {
  features: Features,
  hero: Hero,
  test_slice: TestSlice,
};
